##########################################################################
#                               PATHS                                    #
##########################################################################

# Input and output path of markdown files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
md_folder_path_str:  '/Users/tim/Documents/RPGs/website/taelgarverse-build-md/'

# Markdown entrypoint path
# This has to be md_folder_path_str + '/index.md' when toggles/compile_md == True
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
md_entrypoint_path_str: '/Users/tim/Documents/RPGs/website/taelgarverse-build-md/index.md'

# Output path of HTML files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
html_output_folder_path_str: '/Users/tim/Documents/RPGs/website/taelgarverse-build-html/'

# If extended logging is enabled under toggles/extended_logging
# Extra information is written to this folder
log_output_folder_path_str: '/Users/tim/Documents/RPGs/website/taelgarverse-output/log'

##########################################################################
#                              OPERATIONS                                #
##########################################################################
# Exclude subfolders
# These are relative to obsidian_folder_path_str
# To exclude a folder two levels deep, use level1/level2
exclude_glob:
  - /.obsidian
  - /.trash
  - /.git
  - /.scripts
  - /.backups
  - /.secrets
  - /_templates 
  - .gitignore
  - .gitattributes
  - .DS_Store
  - Organizational Notes.md
  - /Worldbuilding
  - /_DM_

# Number of links a note can be removed from the entrypoint note
# -1 for no max depth
# 0 means only the entrypoint note is processed
# 1 means only direct children are processed (and the entrypoint of course)
# and so forth. NOTE: DOES NOT APPLY TO INCLUSIONS!
max_note_depth: -1

# Safety feature: make a copy of the provided vault, and operate on that, so that bugs are less likely to affect the vault data. 
# Should be fine to turn off if copying the vault takes too long / disk space is too limited.
# The tempdir is automatically removed on exit of the program.
copy_vault_to_tempdir: True

# Determines the function to use to copy your vault over to the tempdir.
# `default` will try to use rsync if it is installed, and otherwise use `shutil`
# `rsync` will do the same, but give a warning when it falls back to shutil
# `shutil` will just use shutil to copy. Use this when rsync is installed but is giving problems.
copy_vault_to_tempdir_method: default

# Enable to print the files being copied
copy_vault_to_tempdir_follow_copy: false

# ObsidianHtml needs to be able to discern between included notes and included files, because included files 
# need to be treated differently. This is a configurable setting because we might've missed certain suffixes
# of files that are includable.
included_file_suffixes: ['jpg', 'jpeg', 'gif', 'png', 'bmp', 'svg', 'mp4', 'webm', 'ogv', 'mov', 'mkv', 'mp3', 'wav', 'm4a', 'ogg', '3gp', 'flac', 'pdf']
video_format_suffixes: ['mp4', 'webm', 'ogv', 'mov', 'mkv']
audio_format_suffixes: ['mp3', 'webm', 'wav', 'm4a', 'ogg', '3gp', 'flac']

# files that should be included via an <embed> tag:
embeddable_file_suffixes: ['pdf'] 

# Used to strip the http url hostpart of a link to get a relative link
# e.g. for value "https://git.com/user/repo/-/wikis/mywiki/" then:
#   "https://git.com/user/repo/-/wikis/mywiki/folder/markdown.md" --> /folder/markdown.md
md_source_host_urls: []

##########################################################################
#                             HTML OUTPUT                                #
##########################################################################

# Will be inputted into the Html template as page title
# Not used anywhere else atm.
site_name: 'TaelgarVerse'

# Use when deploying to https://mydomain.com/html_prefix/ instead of https://mydomain.com/
# use '/html_prefix' (prepend slash, no slash at the end)
html_url_prefix: '/taelgarverse'

# Provide the fullpath to a template file to use instead of standard template. 
# Note that this file must contain at least "{content}" somewhere in the page.
html_template_path_str: ''

# Provide an array of custom inclusions (css, javascript, etc) that you would like to be included in the resultant html
html_custom_inclusions: []
html_custom_footer_inclusions: []

navbar_links: []

file_exports: []
# file_exports:
#   - encoding: binary
#     src: Resources/Includes/favicon.ico
#     dst: favicon.ico
#   - src: Resources/Includes/christmas_snowflakes.js
#     dst: obs.html/static/christmas_snowflakes.js

##########################################################################
#                    OPTIONAL BEHAVIOR / FEATURES                        #
##########################################################################
toggles:
  # Opt-in/-out of Obsidian->Md conversion, set to False when using proper markdown as input
  compile_md: False

  # Opt-in/-out of Md->Html conversion, set to False when only wanting to get proper markdown from Obsidian
  compile_html: True

  # For compatibility with vaults/notes that have the 'Strict Line Breaks' option enabled
  # This is off by default in Obsidian; setting it to True will not insert <br> tags into multi-line paragraphs
  strict_line_breaks: False

  # gitlab is case insensitive, this setting should be true when converting a wiki from that source
  # might also be useful if you have markdown links in your vault
  # note that this does not impact the output, Hello.md will be written to Hello.html
  force_filename_to_lowercase: True

  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: False

  # Can be overwritten ad-hoc by using "obsidianhtml -i config.yml -v" (the -v option)
  verbose_printout: False
  debug_filetree_keys: False

  # Write extra information to log_output_folder_path_str
  extended_logging: False

  # This option should be False for Obsidian->Md, but can be True when compile_md == False
  # Setting it to True will cause an error when two files with the same file name are found anywhere in the input folder
  allow_duplicate_filenames_in_root: False

  # Sometimes linked images that should be local (based on the path) cannot be found.
  # Toggle this to False to disable warnings if that happens.
  warn_on_skipped_image: True

  # This will skip emptying output folders, if you want to implement this yourself
  no_clean: True

  # Whether the markdown interpreter assumes relative path when no / at the beginning of a link
  relative_path_md: True

  # Whether the html paths will be relative. 
  # Note: This is only useful if you want to open the html locally on your machine without using a webserver
  #  and is generally not advised. This will also disable all features that need a webserver to function
  #  such as the graph view.
  relative_path_html: False

  # Whether external http anchor links should have a target of "_blank"
  external_blank: False  

  # Will preserve inline tags. This will give polluted markdown output
  preserve_inline_tags: True
  
  features:
    styling: 
      layout: documentation               # documentation, tabs, minimal
      max_note_width: 120rem              # not supported for layout: tabs
      add_toc: True                       # add "[TOC]" (Table of Contents) when missing
      toc_pane: True                      # removes table of contents from the note and puts it in the right pane (not supported for layout:tabs)
      flip_panes: False                   # switch right and left pane around. (does nothing unless in documentation layout.)
      add_dir_list: True                  # show directory contents in one of the panes (only documentation layout)
      accent_color: '65, 76, 253'
      loading_bg_color: '255, 255, 255'

    theme_picker:
      enabled: True
      styling:
        show_icon: True

    code_highlight:
      enabled: True
    mermaid_diagrams:
      enabled: True
    callouts:
      enabled: True
    math_latex:
      enabled: True
    backlinks:                  # Show backlinks at the bottom of each note
      enabled: True
    embedded_note_titles:
      enabled: True

    search:
      enabled: True
      styling:
        show_icon: True

    embedded_search:
      enabled: False

    tags_page:
      enabled: True
      styling:
        show_icon: True
        show_in_note_footer: True

    dataview:
      enabled: False
      folder: 'obs.html/export'       # relative to the vault being processed. this folder should always be in the vault

    folder_notes:
      enabled: True
      placement: 'inside folder'     # 'inside folder' , 'outside folder' 
      naming: 'folder name'           # 'folder name', 'index', 'aurkibidea', 'etc'

    eraser:
      enabled: True

    breadcrumbs:
      enabled: False

    # Include code to build the graph view per page 
    graph:
      enabled: True                   # Include code to build the graph view per page (default: True)
      templates:
        - id: 2d
          name: 2d
          path: builtin<2d>
        - id: 3d
          name: 3d
          path: builtin<3d>
      styling:
        show_icon: True
      coalesce_force: '-30'

    # Create an index.md with links to notes that have one of the given tags.
    # This index.md will serve as the entrypoint.
    # !! Enabling this feature will overwrite obsidian_entrypoint_path_str and md_entrypoint_path_str
    create_index_from_tags:
      enabled: False
      add_links_in_graph_tree: True
      tags: []
      sort:
        method: 'none'          # <key_value, creation_time, modified_time, none>    ! created_time not available on Linux!
        key_path: ''            # empty for top level, use ':' to go down multiple levels
        value_prefix: ''        # in case of multiple values under key_path, match on this prefix, and then remove prefix
        reverse: false          # false/true reverses output
        none_on_bottom: true    # will put notes at the bottom that do not have the sort key, otherwise at the top
      exclude_paths:            # don't included these paths in the dir list
       - ".gitignore"

    rss:
      enabled: False
      host_root: 'https://localhost:8000/'
      styling: 
        show_icon: True
      channel: 
        title: 'Notes'
        website_link: '<https://your website.com>'
        description: '<your description>'
        language_code: 'en-us'
        managing_editor: 'n/a'
        web_master: 'n/a'
      items:
        selector: 
          match_keys: []
          exclude_keys: []
          include_subfolders: []
          exclude_subfolders: ['.git','obs.html']
          exclude_files: ['not_created.html', 'index.html']
        description:
          selectors:
            - ['yaml','rss:description']
            - ['first-paragraphs', 2, '<br/><br/>']
            - ['first-header', 1]
        title: 
          selectors: 
            - ['yaml','rss:title']
            - ['first-header', 1]
            - ['path', ['parent',1], '/ ', ['stem']]
        publish_date: 
          selectors: 
            - ['yaml','rss:publish_date']
            - ['yaml_strip','tags',['date/']]
          iso_formatted: True
          format_string: '' #'%Y-%m-%d'

    create_index_from_dir_structure:
      enabled: True
      verbose: False
      rel_output_path: 'obs.html/dir_index.html'
      styling: 
        show_icon: True
      exclude_subfolders:
        - ".git"
        - "__src"
        - "obs.html"
        - "assets"
      exclude_files:
        - "favicon.ico"
        - "not_created.html"
        - ".DS_Store"
        - ".gitignore"